test_gitlab_configuration:
  stage: .pre
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags: ["arch:amd64"]
  rules:
    - !reference [.on_gitlab_changes]
  script:
    - source /root/.bashrc
    - export GITLAB_TOKEN=$($CI_PROJECT_DIR/tools/ci/aws_ssm_get_wrapper.sh $GITLAB_FULL_API_TOKEN_SSM_NAME)
    - inv -e linter.gitlab-ci
    - inv -e linter.job-change-path
    - inv -e linter.gitlab-change-paths

test_gitlab_compare_to:
  stage: .pre
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags: ["arch:amd64"]
  rules:
    - !reference [.on_gitlab_changes]
  script:
    - source /root/.bashrc
    - export GITLAB_TOKEN=$($CI_PROJECT_DIR/tools/ci/aws_ssm_get_wrapper.sh $GITLAB_FULL_API_TOKEN_SSM_NAME)
    - !reference [.setup_agent_github_app]
    - pip install -r tasks/requirements.txt
    - inv pipeline.compare-to-itself

ugly_early_debug:
  stage: .pre
  tags: ["arch:arm64"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/linux-glibc-2-23-arm64_test_only:v40686155-8be96841
  script:
    - file /usr/local/rvm/rubies/ruby-2.7.2/lib/libruby.so.2.7.2
