test_gitlab_compare_to:
  stage: .pre
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags: ["arch:amd64"]
  rules:
    - !reference [.on_gitlab_changes]
  script:
    - source /root/.bashrc
    - source $CI_PROJECT_DIR/tools/ci/open_file_descriptor.sh
    - $CI_PROJECT_DIR/tools/ci/aws_ssm_get_wrapper.sh $DOCKER_REGISTRY_LOGIN_SSM_KEY
    - export GITLAB_TOKEN=$(pop_front)
    - !reference [.setup_agent_github_app]
    - echo token $GITLAB_TOKEN
    - echo key $GITHUB_KEY_B64
    - echo app $GITHUB_APP_ID
    - echo ins $GITHUB_INSTALLATION_ID
